from marshmallow import Schema, fields


class AutoCompleteSchema(Schema):
    question = fields.String(description="Question")
    time = fields.DateTime(description="Time")
    email = fields.Email(description="Email")

class QuestionSchema(Schema):
    question = fields.String(description="Question section")

class AnswerSchema(Schema):
    question = fields.String(description="Question section")
    answer = fields.String(description="Answer in plain text")
    slice_id = fields.Integer(description="slice_id generated by Quotron.")
    # slice = fields.Nested(ChartEntityResponseSchema)

class ColumnHistorySchema(Schema):
    column_name = fields.String(description='column name')
    id = fields.String(description='id or pk value of column')
    expression = fields.String(description='SQL expression of calculated columns')
    changed_on = fields.String(description='changed date-time (ISO format) of the column  value')
    description = fields.String(description='description of column')
    type = fields.String(description='Type of string')
